ProyectoDjango1/urls.py
from django.conf.urls import include
from django.contrib import admin

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views


from django.contrib.auth.views import login, logout_then_login

#configuracion de media
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
##################3

from django.views.generic.base import RedirectView
from allauth.account.views import *


urlpatterns = [
	#1.8.1 circulos
	url(r'^zonas/$', app.views.Zonas, name="zonas"),
	#1.6 FIltros
    url(r'^filtro/([0-9]*)/$', app.views.Filtro, name='filtro'),
	url(r'insertar/', app.views.insertar, name='insertar'),
    url(r'contador/', app.views.contador.as_view(), name='contador'),
    # Examples:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$',RedirectView.as_view(url='accounts/login/')),
	url(r'^denuncia/$', app.views.Denuncia, name='denuncia_view'),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^mapa/$',app.views.Mapa.as_view(),name='mapa_view'),
	url(r'^noticia/(?P<pk>\d+)/$', app.views.Noticia, name='noticia_view'),
	url(r'^perfil/(?P<pk>\d+)/$',app.views.Perfil,name='perfil_view'),
	url(r'^perfiluser/$',app.views.PerfilUser,name='perfilUser_view'),
	url(r'^actualizar/(?P<pk>\d+)/$',app.views.UpdatePerfil.as_view(),name='actualizarPerfil_view'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
"""
Definition of models.
"""

from django.db import models

from django.contrib.auth.models import User


class Usuario_m(models.Model):
	Nombre = models.OneToOneField(User,on_delete=models.CASCADE)
	Telefono = models.IntegerField(null=True, blank=True)
	Direccion = models.CharField(max_length=100,null=True, blank=True)
	Avatar = models.FileField(upload_to='avatar/%Y/%m/%d', null=True, blank=True)

	def __unicode__(self):
		return self.Nombre.username



 
class Denuncia_m(models.Model):
	user=models.ForeignKey(User)
	titulo=models.CharField(max_length=50)
	descripcion=models.TextField()
	latitud=models.FloatField()
	longitud=models.FloatField()
	lista_categorias=(
        (1,'Reten'),
		(2,'Bache'),
		(3,'Accidente'),
		(4,'Reparaciones'),
		(5,'Evento'),
		(6,'Otro')
        )
	categoria=models.IntegerField(choices=lista_categorias, verbose_name=u"Categoria",null=True, blank=True)
	lista_nivel=(
		(1,'Totalmente bloqueado'),
		(2,'Parcialmente bloqueado'),
		(3,'Ninguno')
		)
	nivel=models.IntegerField(choices=lista_nivel, verbose_name=u"Nivel",null=True, blank=True)
	 #1.6.1 Votos y rangos
	estado=models.NullBooleanField(verbose_name=u"Activado",null=True, blank=True)
    #1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
	reportado=models.NullBooleanField(verbose_name=u"Reportado",null=True, blank=True),
	#1.9.1 Validaciones
	hasta=models.DateTimeField(null=True, blank=True)
	def __unicode__(self):
		return self.titulo

class imagenes_m(models.Model):
	denunciaA=models.ForeignKey(Denuncia_m, null=True, blank=True)
	imagen=models.FileField(upload_to='img/%Y/%m/%d',null=True, blank=True)
	
	def __unicode__(self):
		return self.denunciaA.user.username

class videos_m(models.Model):
    denunciaB=models.ForeignKey(Denuncia_m, null=True, blank=True)
    video=models.FileField(upload_to='img/%Y/%m/%d',null=True, blank=True)
    
    def __unicode__(self):
			return self.denunciaB.user.username
	
class Comentario_m(models.Model):
	user=models.ForeignKey(User)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	comentario=models.CharField(max_length=250)
	
	def __unicode__(self):
		return self.comentario

#1.6.1 Likes, rangos y reportados
class Rango_m(models.Model):
	usuario=models.ForeignKey(User,null=True, blank=True)
	buenos=models.IntegerField(null=True, blank=True)
	malos=models.IntegerField(null=True, blank=True)
	#1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
class Favor_m(models.Model):
	usuario=models.ForeignKey(User,null=True, blank=True)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	#1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
class Contra_m(models.Model):
	usuario=models.ForeignKey(User,null=True, blank=True)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	#1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
class Reportados_m(models.Model):
    usuario=models.ForeignKey(User,null=True, blank=True)
    denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
    #1.7 Reportes
    fecha=models.DateTimeField(auto_now=True)
#Fin 1.6.1

#1.8.1 Circulos
class Circulos_m(models.Model):
	x=models.FloatField(null=True, blank=True)
	y=models.FloatField(null=True, blank=True)
	cantidad=models.IntegerField(null=True, blank=True)
	fecha=models.DateField(auto_now=True)
#Fin 1.8.1

app/templates/app/contador.html
{% extends "app/base.html" %}


{% block content %}

{% for x in object_list %}
    <p>{{ forloop.counter + 10 }}</p>
{%endfor%}
{% endblock content %}

app/templates/app/index.html
{% extends "app/base.html" %}

app/templates/app/noticia.1_res.html
{% extends "app/base.html" %}

{% block estilos %}

<script src="https://use.fontawesome.com/a368244793.js"></script>


<style>

		.foot{
			height: 50px;
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
			background: #34495e !important;
		}
		.img{
			min-width: 100%;
			min-height: 200px;
			max-height: 400px;
			background: blanchedalmond;
		}

		.form_comentarios textarea {
			width: 100%;
			height: 84px;
			max-width: 100%;
			min-width: 100%;
			min-height: 84px;
			max-height: 300px;
			padding: 10px;
			font-family: 'Roboto', sans-serif;
			line-height: 30px;
			border: 1px solid #4b65d1;
			margin-bottom: 20px;
		}
		.cabecera{
			background: #34495e !important;
		}

		.perfil{
			margin-right: 10px;
		}

		.bot{
			min-width: 30px;
			min-height: 50px;
			
			margin: 0;
			border: 0;
			background: transparent;
			
			
		}

		.pt{
			font-size: 50px;
			
		}
		
</style>
{% endblock estilos %}


{% block content %}
{% load staticfiles %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col-12 mt-3">
			<div class="carousel slide" id="principal-carousel" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#principal-carousel" data-slid-to="0" class="active"></li>
					<li data-target="#principal-carousel" data-slid-to="1"></li>
					<li data-target="#principal-carousel" data-slid-to="2"></li>
				</ol>


				<a href="#principal-carousel" class="carousel-control-prev" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Anterior</span>
				</a>

				<a href="#principal-carousel" class="carousel-control-next" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Siguiente</span>
				</a>
			</div>
		</div>
	</div>
</div>

{% for x in ctx %}
	<div class="container ">
		<div class="row">
			<div class="col-12 text-center mb-3 pb-3 h1">{{x.titulo}}</div>
				<div id="carouselExampleIndicators" class=" col-12 carousel slide" data-ride="carousel">
				<!--
					<ol class="carousel-indicators">
					  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
				-->
					<div class="carousel-inner">
						<!-- imagenes -->
						{% for y in ctx2 %}				
							{% if forloop.first %}
								<div class="carousel-item  active  ">
									<img class="d-block img img-fluid " src="{{y.imagen.url}}" alt="First slide">
								</div>
							{% else %}
								<div class="carousel-item ">
									<img class="d-block img img-fluid " src="{{y.imagen.url}}" alt="First slide">
								</div>
							{% endif %}
						
						{% endfor %}
		
						<!-- VIDEOS -->
						{% for z in ctx3 %}
						<div class="carousel-item">
							
							{% if z.video %}			
								<img class="d-block w-90 img img-fluid" src="{{z.video.url}}" alt="First slide">
							{% endif %}
								
						</div>
						{% endfor %}
		
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
					  <span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					  <span class="carousel-control-next-icon" aria-hidden="true"></span>
					  <span class="sr-only">Next</span>
					</a>
				</div>


				<!--Inicia 1.6.2 Votos-->
			<div class="col-12 mt-5">
					<!--1.6.3 reputacion-->
					Reputaci&oacute;n: {{nivel}}%
					<!--Fin 1.6.3-->
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if x == 1 or ninguno == False %}
						<!--
							<input type="submit" value="Contra" name="contra"/>
							<input type="submit" value="Favor" name="favor" />
						-->
							<button type="submit" value="Contra" name="contra" class="bot">
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot">
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>
							
						{% else %}
						{% if x == 2 or favor == True %}
						<!--
							<input type="submit" value="Contra" name="contra" />
							<input type="submit" value="Favor" name="favor" disabled/>
						-->
							<button type="submit" value="Contra" name="contra" class="bot">
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot" disabled>
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>
						{% endif %}
						{% if x == 3 or favor == False %}
						<!--
							<input type="submit" value="Contra" name="contra" disabled/>
							<input type="submit" value="Favor" name="favor" />
						-->
							<button type="submit" value="Contra" name="contra" class="bot" disabled>
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot">
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>

						{% endif %}
						{% endif %}
						
	
					</form>
					<!--Fin 1.6.2-->
					<!--Inicia 1.6.3 reportes-->
					Reportar
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if reportado == True %}
						<input type="submit" value="Reportar" name="reportar" disabled />
						{% endif %}
						{% if reportado == False %}
						<input type="submit" value="Reportar" name="reportar" />
						{% endif %}
					</form>
	<!--Fin 1.6.3-->
			
			<div class="col-12 mt-5">
				<p class="h5">{{x.descripcion}}</p>
			</div>
			<div class="col-12 mt-5">
					<form method = "POST" class="form_comentarios d-flex justify-content-end flex-wrap">
						{% csrf_token %} 

						<input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

						<input type="hidden" name="denuncia" required="" id="id_denuncia" value="{{x.id}}">

						<textarea name="comentario" required id="id_comentario" maxlength="250" placeholder="Comentario"></textarea>
						
						<input type="submit" value="Comentar">
					</form>
				
			</div>
			<div class="col-12 mt-5 pb-5 mb-5">
					<h2>Comentarios</h2>
					
			
				{% for a in ctx5 %}
				<div class="media">
					
					{% if a.Avatar %}
					
						{% ifequal a.Avatar 'None' %}
							<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="300px" height="300px" alt="Imagen aleatoria">
						{% else %}
							<img class="perfil" src="{{a.Avatar.url}}" width="64px" height="64px"/>
						{% endifequal %}
						
				{% else %}
					<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="64px" height="64px" alt="Imagen aleatoria">
			
				{% endif %}
				
					<div class="media-body">
						<p class="nombre"><a href="{% url 'perfil_view' pk=a.Nombre_id %}">{{a.username}}</a></p>
						<p class="comentario">
							{{a.comentario}}
						</p>
						

					</div>
				</div>
				<hr>
				{% endfor %}		
			</div>
			
		</div>
	</div>

{% endfor%}


{% endblock content %}
	

app/templates/app/noticia.html
{% extends "app/base.html" %}
{% block titulo %}Noticias {% endblock titulo %}
{% block estilos %}

<script src="https://use.fontawesome.com/a368244793.js"></script>


<style>

		.foot{
			height: 50px;
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
			background: #34495e !important;
		}
		.img{
			
			
			max-height: 400px;
			min-height: 400px;
			
			margin: auto;
		}

		.img-center{
			margin: auto;
		}

		.img-seg{
			min-width: 100%;
			min-height: 200px;
			max-height: 400px;
			background: blanchedalmond;
		}
		.form_comentarios textarea {
			width: 100%;
			height: 84px;
			max-width: 100%;
			min-width: 100%;
			min-height: 84px;
			max-height: 300px;
			padding: 10px;
			font-family: 'Roboto', sans-serif;
			line-height: 30px;
			border: 1px solid #4b65d1;
			margin-bottom: 20px;
		}
		.cabecera{
			background: #34495e !important;
		}

		.perfil{
			margin-right: 10px;
		}

		.bot{
			min-width: 30px;
			min-height: 50px;
			
			margin: 0;
			border: 0;
			background: transparent;
			
			
		}

		.pt{
			font-size: 50px;
			
		}

		.flecha{
			color: black;
			font-size: 30px;
			font-weight: bold;
		}
		

		
</style>
{% endblock estilos %}


{% block content %}
{% load staticfiles %}
 
 {% for x in ctx %}
 <h1 class="mt-5 pt-5 mb-3 pb-3 text-center">{{x.titulo}}</h1>
	<div class="container">
		<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">	
			<div class="carousel-inner">
					{% for y in ctx2 %}				
					{% if forloop.first %}
						<div class="carousel-item  active  ">
							<img class="d-block img img-fluid " src="{{y.imagen.url}}" alt="First slide">
						</div>
					{% else %}
						<div class="carousel-item ">
							<img class="d-block img img-fluid " src="{{y.imagen.url}}" alt="First slide">
						</div>
					{% endif %}
				
				{% endfor %}

				<!-- VIDEOS -->
				{% for z in ctx3 %}
					{% if z.video %}
					<!-- 	<div class="carousel-item">		
							<img class="d-block w-90 img img-fluid" src="{{z.video.url}}" alt="First slide">		
						</div> -->
					<div class="carousel-item align-items-center">	
						<video class="img col  " controls>
							<source class="img-center" src="{{z.video.url}}" type="video/mp4" />
						</video>
					</div>
					{% endif %}
				{% endfor %}
			</div>
			<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
			<span  aria-hidden="true">
				<i class="fa fa-chevron-left flecha" aria-hidden="true"></i>
			</span>
			<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
			<span  aria-hidden="true">
				<i class="fa fa-chevron-right flecha" aria-hidden="true"></i>				
			</span>
			<span class="sr-only">Next</span>
			</a>
		</div>
		
	</div>

				<!--Inicia 1.6.2 Votos-->
			<div class="col-12 mt-5">
					<!--1.6.3 reputacion-->
					Reputaci&oacute;n: {{nivel}}%
					<!--Fin 1.6.3-->
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if x == 1 or ninguno == False %}
						<!--
							<input type="submit" value="Contra" name="contra"/>
							<input type="submit" value="Favor" name="favor" />
						-->
							<button type="submit" value="Contra" name="contra" class="bot">
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot">
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>
							
						{% else %}
						{% if x == 2 or favor == True %}
						<!--
							<input type="submit" value="Contra" name="contra" />
							<input type="submit" value="Favor" name="favor" disabled/>
						-->
							<button type="submit" value="Contra" name="contra" class="bot">
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot" disabled>
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>
						{% endif %}
						{% if x == 3 or favor == False %}
						<!--
							<input type="submit" value="Contra" name="contra" disabled/>
							<input type="submit" value="Favor" name="favor" />
						-->
							<button type="submit" value="Contra" name="contra" class="bot" disabled>
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot">
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>

						{% endif %}
						{% endif %}
						
	
					</form>
					<!--Fin 1.6.2-->
					<!--Inicia 1.6.3 reportes-->
					Reportar
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if reportado == True %}
						
						<input type="submit" value="Reportar" name="reportar" disabled />
						
						{% endif %}
						{% if reportado == False %}
					
						<input type="submit" value="Reportar" name="reportar" />
						
						{% endif %}
					</form>
	<!--Fin 1.6.3-->
			
			<div class="col-12 mt-5">
				<p class="h5">{{x.descripcion}}</p>
			</div>
			<div class="col-12 mt-5">
					<form method = "POST" class="form_comentarios d-flex justify-content-end flex-wrap">
						{% csrf_token %} 

						<input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

						<input type="hidden" name="denuncia" required="" id="id_denuncia" value="{{x.id}}">

						<textarea name="comentario" required id="id_comentario" maxlength="250" placeholder="Comentario"></textarea>
						
						<input type="submit" value="Comentar">
					</form>
				
			</div>
			<div class="col-12 mt-5 pb-5 mb-5">
					<h2>Comentarios</h2>
					
			
				{% for a in ctx5 %}
				<div class="media">
					
					{% if a.Avatar %}
					
						{% ifequal a.Avatar 'None' %}
							<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="300px" height="300px" alt="Imagen aleatoria">
						{% else %}
							<img class="perfil" src="{{a.Avatar.url}}" width="64px" height="64px"/>
						{% endifequal %}
						
				{% else %}
					<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="64px" height="64px" alt="Imagen aleatoria">
			
				{% endif %}
				
					<div class="media-body">
						<p class="nombre"><a href="{% url 'perfil_view' pk=a.Nombre_id %}">{{a.username}}</a></p>
						<p class="comentario">
							{{a.comentario}}
						</p>
						

					</div>
				</div>
				<hr>
				{% endfor %}		
			</div>
			
		</div>
	</div>

{% endfor%}


{% endblock content %}
	

app/templates/app/noticia_resplado.html
{% extends "app/base.html" %}

{% block estilos %}

<style>

		.foot{
			height: 50px;
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
		}
		.img{
			min-width: 100%;
			min-height: 200px;
			max-height: 400px;
			background: blanchedalmond;
		}

		.form_comentarios textarea {
			width: 100%;
			height: 84px;
			max-width: 100%;
			min-width: 100%;
			min-height: 84px;
			max-height: 300px;
			padding: 10px;
			font-family: 'Roboto', sans-serif;
			line-height: 30px;
			border: 1px solid #4b65d1;
			margin-bottom: 20px;
		}
</style>
{% endblock estilos %}


{% block content %}
{% load staticfiles %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col-12 mt-3">
			<div class="carousel slide" id="principal-carousel" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#principal-carousel" data-slid-to="0" class="active"></li>
					<li data-target="#principal-carousel" data-slid-to="1"></li>
					<li data-target="#principal-carousel" data-slid-to="2"></li>
				</ol>

				<div class="carousel-inner">
					<div class="carousel-item active">
						<img src="img/carousel1.jpg" class="w-100" alt="">
					</div>
					<div class="carousel-item">
						<img src="img/carousel2.jpg" alt="">
					</div>
					<div class="carousel-item">
						<img src="img/carousel3.jpg" alt="">
					</div>
				</div>

				<a href="#principal-carousel" class="carousel-control-prev" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Anterior</span>
				</a>

				<a href="#principal-carousel" class="carousel-control-next" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Siguiente</span>
				</a>
			</div>
		</div>
	</div>
</div>
{% for x in ctx %}
	<div class="container mt-5 pt-5">
		<div class="row">
			<div class="col-12 text-center mb-3 h1">{{x.titulo}}</div>
		
			
				<div id="carouselExampleIndicators" class=" col-12 carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
					  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner">
						<div class="carousel-item  active  ">
							<img class="d-block img img-fluid" src="http://qnimate.com/wp-content/uploads/2014/03/images2.jpg" alt="Second slide">
						</div>
						<!-- imagenes -->
						{% for y in ctx2 %}
						<div class="carousel-item ">
							<img class="d-block img img-fluid " src="{{y.img.url}}" alt="First slide">
						</div>
						{% endfor %}
		
						<!-- VIDEOS -->
						{% for z in ctx3 %}
						<div class="carousel-item">
							
							{% if z.video %}
								
								<img class="d-block w-90 img img-fluid" src="{{z.video.url}}" alt="First slide">
							{% endif %}
								
						</div>
						{% endfor %}
		
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
					  <span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					  <span class="carousel-control-next-icon" aria-hidden="true"></span>
					  <span class="sr-only">Next</span>
					</a>
				</div>
			
			<div class="col-12 mt-5">
				<p class="h5">{{x.descripcion}}</p>
			</div>
			<div class="col-12 mt-5">
					<form method = "POST" class="form_comentarios d-flex justify-content-end flex-wrap">
						{% csrf_token %} 

						<input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

						<input type="hidden" name="denuncia" required="" id="id_denuncia" value="{{x.id}}">

						<textarea name="comentario" required id="id_comentario" maxlength="250" placeholder="Comentario"></textarea>
						
						<input type="submit" value="Comentar">
					</form>
				
			</div>
			<div class="col-12 mt-5 pb-5 mb-5">
					<h2>Comentarios</h2>
					
			
				{% for a in ctx4 %}
				<div class="media">
					
		
					{% for b in ctx5  %}
					{% ifequal b.Nombre_id a.user_id %}
						{% if b.Avatar %}
							<img class="perfil" src="{{b.Avatar.url}}" width="64px" height="64px" alt="Imagen agregada por usuario">
					
						{% else %}
							<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="64px" height="64px" alt="Imagen aleatoria">
						
						{% endif %}
					{% endifequal %}

					{% ifnotequal b.Nombre_id a.user_id %}			
							<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="64px" height="64px" alt="Imagen aleatoria">				
					{% endifnotequal %}
					
				{% endfor %}
					<div class="media-body">
						<p class="nombre"><a href="{% url 'perfil_view' pk=a.user.id %}">{{a.user}}</a></p>
						<p class="comentario">
							{{a.comentario}}
						</p>
						<p>{{a.user_id}}</p>

					</div>
				</div>
				<hr>
				{% endfor %}		
			</div>
			
		</div>
	</div>

{% endfor%}

{% endblock content %}
	

app/templates/app/registrar.html
{% extends "app/base.html" %}


{% block content %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col">
			<form method="POST" class="form-control" enctype="multipart/form-data">
				{% csrf_token %}
				 
				<p>
					<label for="id_Nombre">Nombre:</label> 
					<select name="Nombre" required id="id_Nombre" >
						<option value="1">{{user.username}}</option>
					</select>
				</p>
				  <p><label for="id_Telefono">Telefono:</label> <input type="number" name="Telefono" id="id_Telefono" /></p>

				  <p><label for="id_Direccion">Direccion:</label> <input type="text" name="Direccion" id="id_Direccion" maxlength="100" /></p>
				  
				  <p><label for="id_Avatar">Avatar:</label> <input type="file" name="Avatar" id="id_Avatar" /></p>

				 <input type="submit" value="Actualizar">
				 <input type="reset" value="Cancel">
			</form>	
		</div>
	</div>
</div>

{% endblock content %}